delete from asientosmov where idasiento in (select idasiento from asientosdia );
delete from asientosdia ;
truncate cobros ;
truncate aneiva ;
truncate detadoci ;
truncate cheques;
truncate detadocd;
--delete from detadocb where isconfbanc;
truncate detadocp;
truncate detadocs;
truncate detadocl;
truncate importd;
truncate importf;
delete from impconte;
delete from contenedord;
delete from import;
truncate producegr;
truncate producing;
delete from produccion;
truncate saldoscon ;
delete from saldosci;
delete from saldosib;
delete from saldosi;
truncate saldosb;
truncate retenreci;
delete from cheques;
delete from documents ;
truncate horaex;
truncate feriados;
truncate conteof;
update bloqueos set islock='f';
truncate auditoria;
------
delete from preciosv;
delete from saldosib;
delete from saldosi;
delete from activosf;
delete from items;
